export const colors = {
    primary: '#1a56db',
    primaryDark: '#1240a8',
    primaryLight: '#e8efff',
    success: '#0e9f6e',
    danger: '#f05252',
    warning: '#ff9800',
    bg: '#f4f6fb',
    card: '#fff',
    border: '#e2e8f0',
    text: '#1a202c',
    textMuted: '#64748b',
    shadow: '0 2px 8px rgba(0,0,0,0.08)',
};

export const styles = {
    sectionHeader: {
        display: 'flex' as const,
        alignItems: 'center' as const,
        justifyContent: 'space-between' as const,
        marginBottom: '20px',
    },
    sectionTitle: {
        fontSize: '18px',
        fontWeight: 700,
        color: colors.text,
    },
    filterBar: {
        display: 'flex' as const,
        gap: '8px',
        flexWrap: 'wrap' as const,
        marginBottom: '16px',
        alignItems: 'center' as const,
    },
    filterInput: {
        flex: 1,
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        padding: '8px 12px',
        fontSize: '13px',
        outline: 'none',
        backgroundColor: colors.card,
        color: colors.text,
        minWidth: '200px',
    },
    filterSelect: {
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        padding: '8px 12px',
        fontSize: '13px',
        outline: 'none',
        backgroundColor: colors.card,
        color: colors.text,
        cursor: 'pointer',
    },
    card: {
        background: colors.card,
        borderRadius: '10px',
        boxShadow: colors.shadow,
        padding: '16px',
    },
    table: {
        width: '100%',
        borderCollapse: 'collapse' as const,
        fontSize: '13px',
    },
    tableHeader: {
        background: '#f8fafc',
        padding: '10px 12px',
        textAlign: 'left' as const,
        fontWeight: 600,
        color: colors.textMuted,
        borderBottom: `1px solid ${colors.border}`,
        whiteSpace: 'nowrap' as const,
    },
    tableCell: {
        padding: '10px 12px',
        borderBottom: `1px solid ${colors.border}`,
        color: colors.text,
    },
    tableRow: {
        backgroundColor: colors.card,
    },
    tableRowHover: {
        backgroundColor: '#f8fafc',
    },
    btn: {
        padding: '8px 16px',
        borderRadius: '8px',
        border: 'none',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 600,
        display: 'inline-flex' as const,
        alignItems: 'center' as const,
        gap: '6px',
        transition: 'all 0.2s',
    },
    btnPrimary: {
        backgroundColor: colors.primary,
        color: '#fff',
    },
    btnPrimaryHover: {
        backgroundColor: colors.primaryDark,
    },
    btnOutline: {
        backgroundColor: colors.card,
        border: `1px solid ${colors.border}`,
        color: colors.text,
    },
    btnOutlineHover: {
        backgroundColor: colors.bg,
    },
    btnSm: {
        padding: '6px 12px',
        fontSize: '12px',
        borderRadius: '6px',
    },
    badge: {
        display: 'inline-block',
        padding: '4px 10px',
        borderRadius: '20px',
        fontSize: '11px',
        fontWeight: 600,
    },
    badgePending: {
        backgroundColor: '#ffe4e6',
        color: '#be123c',
    },
    badgeOpen: {
        backgroundColor: '#dbeafe',
        color: '#1a56db',
    },
    badgeProgress: {
        backgroundColor: '#fef3c7',
        color: '#d97706',
    },
    badgeClosed: {
        backgroundColor: '#d1fae5',
        color: '#065f46',
    },
    badgeHold: {
        backgroundColor: '#f3e8ff',
        color: '#7c3aed',
    },
    badgeCancel: {
        backgroundColor: '#f1f5f9',
        color: '#475569',
    },
    badgeReject: {
        backgroundColor: '#fef2f2',
        color: '#dc2626',
    },
    badgeApprove: {
        backgroundColor: '#d1fae5',
        color: '#065f46',
    },
    badgeWarranty: {
        backgroundColor: '#e0e7ff',
        color: '#4338ca',
    },
    modalOverlay: {
        position: 'fixed' as const,
        inset: 0,
        background: 'rgba(0,0,0,0.5)',
        zIndex: 1000,
        display: 'flex' as const,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        padding: '16px',
    },
    modal: {
        background: colors.card,
        borderRadius: '14px',
        width: '100%',
        maxWidth: '900px',
        maxHeight: '90vh',
        overflowY: 'auto' as const,
        boxShadow: '0 20px 60px rgba(0,0,0,0.2)',
    },
    modalHeader: {
        padding: '16px 20px',
        borderBottom: `1px solid ${colors.border}`,
        display: 'flex' as const,
        alignItems: 'center' as const,
        justifyContent: 'space-between' as const,
        position: 'sticky' as const,
        top: 0,
        background: colors.card,
        zIndex: 1,
    },
    modalTitle: {
        fontSize: '16px',
        fontWeight: 700,
        color: colors.text,
    },
    closeBtn: {
        background: 'none',
        border: 'none',
        fontSize: '20px',
        cursor: 'pointer',
        color: colors.textMuted,
        padding: '4px 8px',
        borderRadius: '6px',
    },
    modalBody: {
        padding: '20px',
        maxHeight: 'calc(90vh - 130px)',
        overflowY: 'auto' as const,
    },
    modalFooter: {
        padding: '14px 20px',
        borderTop: `1px solid ${colors.border}`,
        display: 'flex' as const,
        justifyContent: 'flex-end',
        gap: '10px',
        position: 'sticky' as const,
        bottom: 0,
        background: colors.card,
    },
    formGrid: {
        display: 'grid' as const,
        gridTemplateColumns: 'repeat(2, 1fr)',
        gap: '12px',
        marginBottom: '16px',
    },
    formGroup: {
        display: 'flex' as const,
        flexDirection: 'column' as const,
        gap: '4px',
    },
    formLabel: {
        fontSize: '12px',
        fontWeight: 600,
        color: colors.textMuted,
    },
    formInput: {
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        padding: '8px 12px',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: colors.card,
        outline: 'none',
    },
    formInputFocus: {
        borderColor: colors.primary,
    },
    sectionDivider: {
        borderTop: `2px solid ${colors.primary}`,
        margin: '18px 0',
        paddingTop: '14px',
    },
    sectionHeader2: {
        fontSize: '14px',
        fontWeight: 700,
        marginBottom: '14px',
        color: colors.text,
    },
    divider: {
        border: 'none',
        borderTop: `1px solid ${colors.border}`,
        margin: '16px 0',
    },
    loadingText: {
        textAlign: 'center' as const,
        padding: '40px',
        color: colors.textMuted,
    },
    emptyMessage: {
        textAlign: 'center' as const,
        padding: '40px',
        color: colors.textMuted,
        fontSize: '14px',
    },
};
